//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MACHITIETHOADON { get; set; }
        public int SONGAYTHUE { get; set; }
        public decimal DONGIA { get; set; }
        public decimal THANHTIEN { get; set; }
        public Nullable<int> MAHOADON { get; set; }
        public Nullable<int> MAPHONG { get; set; }
        public Nullable<int> MAPHIEUTHUE { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHIEUTHUE PHIEUTHUE { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
