CREATE DATABASE QUANLIKHACHSAN 
USE QUANLIKHACHSAN
SET DATEFORMAT DMY
GO 
CREATE TABLE NGUOIDUNG ( 
MANGUOIDUNG INT IDENTITY PRIMARY KEY , 
TENNGUOIDUNG NVARCHAR(50) NOT NULL , 
TENDANGNHAP NVARCHAR(50) NOT NULL, 
MATKHAU NVARCHAR(50) NOT NULL, 
QUYENTRUYCAP NVARCHAR(50) NOT NULL, 
ANHDAIDIEN INT NOT NULL
) 
CREATE TABLE THAMSO( 
SOKHTOIDA1PHONG INT PRIMARY KEY, 
PHUTHU MONEY NOT NULL, 
HESOKHNUOCNGOAI INT NOT NULL
) 
CREATE TABLE LOAIPHONG ( 
MALOAIPHONG INT IDENTITY PRIMARY KEY , 
TENLOAIPHONG NVARCHAR(50) NOT NULL, 
DONGIA MONEY NOT NULL,
GHICHU NVARCHAR(200)
)
CREATE TABLE PHONG ( 
MAPHONG INT IDENTITY PRIMARY KEY , 
TENPHONG NVARCHAR(50) NOT NULL, 
GHICHU NVARCHAR(70) NOT NULL, 
TINHTRANG NVARCHAR(50) NOT NULL, 
MALOAIPHONG INT  FOREIGN KEY (MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG)
) 
CREATE TABLE LOAIKHACH( 
MALOAIKHACH INT IDENTITY PRIMARY KEY , 
TENLOAIKHACH NVARCHAR(50) NOT NULL
) 
CREATE TABLE KHACHHANG ( 
MAKHACHHANG INT IDENTITY PRIMARY KEY , 
TENKHACHHANG NVARCHAR(50) NOT NULL, 
SODIENTHOAI NVARCHAR(10) NOT NULL , 
QUOCTICH NVARCHAR (50) NOT NULL , 
CMND NVARCHAR(50) NOT NULL , 
DIACHI NVARCHAR (50) NOT NULL, 
NGAYSINH DATE,
GIOITINH NVARCHAR(10),
MALOAIKHACH INT FOREIGN KEY (MALOAIKHACH) REFERENCES LOAIKHACH (MALOAIKHACH) 
) 
CREATE TABLE PHIEUTHUE ( 
MAPHIEUTHUE INT IDENTITY PRIMARY KEY , 
NGAYBDTHUE DATE NOT NULL, 
MAPHONG INT FOREIGN KEY (MAPHONG) REFERENCES PHONG (MAPHONG),
GHICHU NVARCHAR(30)
) 
CREATE TABLE CHITIETPHIEUTHUE ( 
MACTPHIEUTHUE INT IDENTITY PRIMARY KEY , 
MAKHACHHANG INT FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG (MAKHACHHANG ), 
MAPHIEUTHUE INT FOREIGN KEY (MAPHIEUTHUE) REFERENCES PHIEUTHUE (MAPHIEUTHUE) 
) 
CREATE TABLE HOADON ( 
MAHOADON INT IDENTITY PRIMARY KEY , 
NGAYTHANHTOAN DATE NOT NULL , 
TRIGIA MONEY NOT NULL, 
MAKHACHHANG INT FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG (MAKHACHHANG) 
) 
CREATE TABLE CHITIETHOADON ( 
MACHITIETHOADON INT IDENTITY PRIMARY KEY , 
SONGAYTHUE INT NOT NULL, 
DONGIA MONEY NOT NULL, 
THANHTIEN MONEY NOT NULL, 
MAHOADON INT FOREIGN KEY (MAHOADON) REFERENCES HOADON  (MAHOADON ),
MAPHONG INT FOREIGN KEY(MAPHONG) REFERENCES  PHONG (MAPHONG),
MAPHIEUTHUE INT FOREIGN KEY(MAPHIEUTHUE) REFERENCES  PHIEUTHUE (MAPHIEUTHUE)
) 

INSERT INTO NGUOIDUNG VALUES (N'Quản trị', 'admin','21232F297A57A5A743894A0E4A801FC3',N'Quản lý', 4);
INSERT INTO THAMSO  VALUES (2,50.000,2);
INSERT INTO LOAIPHONG VALUES ('A',150.000,'');
INSERT INTO LOAIPHONG VALUES ('B',170.000,'');
INSERT INTO LOAIPHONG VALUES ('C',200.000,'');
INSERT INTO PHONG VALUES ('C','',N'Mở',2);
INSERT INTO PHONG VALUES ('B','',N'Đóng',1);
INSERT INTO PHONG VALUES ('A','',N'Mở',3);
INSERT INTO LOAIKHACH   VALUES (N'Nội địa');
INSERT INTO LOAIKHACH   VALUES (N'Nước ngoài'); 
INSERT INTO KHACHHANG   VALUES (N'Lê Thị A','0927487841','Viet Nam','2919991232','TPHCM','1/1/2001',N'Nữ',1); 
INSERT INTO KHACHHANG   VALUES (N'Trần Dần','0983843789','USA','117387383','Texas','31/12/2001','Nam',2); 
INSERT INTO PHIEUTHUE  VALUES ('6/7/2021',1, N'Chưa thanh toán'); 
INSERT INTO PHIEUTHUE  VALUES ('1/7/2021',2, N'Đã thanh toán'); 
INSERT INTO PHIEUTHUE  VALUES ('1/7/2021',2, N'Đã thanh toán'); 
INSERT INTO CHITIETPHIEUTHUE VALUES (2,1); 
INSERT INTO CHITIETPHIEUTHUE VALUES (1,2); 
INSERT INTO CHITIETPHIEUTHUE VALUES (1,3); 
INSERT INTO HOADON  VALUES ('2/2/2021',230.000,1); 
INSERT INTO HOADON  VALUES ('6/3/2021',540.000,2); 
INSERT INTO CHITIETHOADON VALUES (1,150.000,150.000,2,1, 2); 
INSERT INTO CHITIETHOADON VALUES (2,170.000,340.000,1,2, 3); 
