//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int SOKHTOIDA1PHONG { get; set; }
        public decimal PHUTHU { get; set; }
        public int HESOKHNUOCNGOAI { get; set; }
    }
}
